name: Build, Sign and Publish Application to Play Store

on:
  release:
    types: [ released ]

jobs:
  publish:
    name: Build, Sign and Publish Application to Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create Google Services file & putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > ./app/google-services.json
      - name: Build with Gradle
        id: build
        run: ./gradlew build
      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEY_PASS }}
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.rocky.moreapps.example
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          inAppUpdatePriority: 5
          whatsNewDirectory: distribution/whatsnew
